import java.math.BigInteger;

/**
 * A main class that will test the BigInteger, ArrayLargeInteger, and LinkedLargeInteger methods
 * 
 * @author Caleb Styles
 * @version November 27, 2021
 */

public class mainMethod {

	public static void main(String[] args) {


		ArrayLargeInteger a1 = new ArrayLargeInteger("43239402304213");
		ArrayLargeInteger a2 = new ArrayLargeInteger("54634534234234234234234");
		ArrayLargeInteger a3 = new ArrayLargeInteger("-432231243545453434234234");
		ArrayLargeInteger a4 = new ArrayLargeInteger("4323412312435436563453453");
		ArrayLargeInteger a5 = new ArrayLargeInteger("12");
		ArrayLargeInteger a6 = new ArrayLargeInteger("-22");
		ArrayLargeInteger a7 = new ArrayLargeInteger("432");
		ArrayLargeInteger a8 = new ArrayLargeInteger("0");
		ArrayLargeInteger a9 = new ArrayLargeInteger("-43");
		ArrayLargeInteger a10 = new ArrayLargeInteger("-34");
		
		LinkedLargeInteger l1 = new LinkedLargeInteger("43239402304213");
		LinkedLargeInteger l2 = new LinkedLargeInteger("54634534234234234234234");
		LinkedLargeInteger l3 = new LinkedLargeInteger("-432231243545453434234234");
		LinkedLargeInteger l4 = new LinkedLargeInteger("4323412312435436563453453");
		LinkedLargeInteger l5 = new LinkedLargeInteger("12");
		LinkedLargeInteger l6 = new LinkedLargeInteger("-22");
		LinkedLargeInteger l7 = new LinkedLargeInteger("432");
		LinkedLargeInteger l8 = new LinkedLargeInteger("0");
		LinkedLargeInteger l9 = new LinkedLargeInteger("-43");
		LinkedLargeInteger l10 = new LinkedLargeInteger("-34");
		
		BigInteger b1 = new BigInteger("43239402304213");
		BigInteger b2 = new BigInteger("54634534234234234234234");
		BigInteger b3 = new BigInteger("-432231243545453434234234");
		BigInteger b4 = new BigInteger("4323412312435436563453453");
		BigInteger b5 = new BigInteger("12");
		BigInteger b6 = new BigInteger("-22");
		BigInteger b7 = new BigInteger("432");
		BigInteger b8 = new BigInteger("0");
		BigInteger b9 = new BigInteger("-43");
		BigInteger b10 = new BigInteger("-34");
		
		long start = 0;
		long finish = 0;
		
		System.out.println("All ArrayList Test Cases: ");
		System.out.println();
		System.out.println("ADD: ");
		start = System.nanoTime();
		System.out.println(a1.add(a2));
		System.out.println(a3.add(a4));
		System.out.println(a5.add(a6));
		System.out.println(a7.add(a8));
		System.out.println(a9.add(a10));
		finish = System.nanoTime();
		System.out.println();
		System.out.println("ADD Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		
		System.out.println("SUBTRACT: ");
		start = System.nanoTime();
		System.out.println(a1.subtract(a2));
		System.out.println(a2.subtract(a1));
		System.out.println(a3.subtract(a4));
		System.out.println(a4.subtract(a3));
		System.out.println(a5.subtract(a6));
		System.out.println(a6.subtract(a5));
		System.out.println(a7.subtract(a8));
		System.out.println(a8.subtract(a7));
		System.out.println(a9.subtract(a10));
		System.out.println(a10.subtract(a9));
		finish = System.nanoTime();
		System.out.println("SUBTRACT Runtime: " + (((finish - start) /10) /1000000.0) + ".");
		System.out.println();
		System.out.println("MAX: ");
		start = System.nanoTime();
		System.out.println(a1.max(a2));
		System.out.println(a3.max(a4));
		System.out.println(a5.max(a6));
		System.out.println(a7.max(a8));
		System.out.println(a9.max(a10));
		finish = System.nanoTime();
		System.out.println("MAX Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("MIN: ");
		start = System.nanoTime();
		System.out.println(a1.min(a2));
		System.out.println(a3.min(a4));
		System.out.println(a5.min(a6));
		System.out.println(a7.min(a8));
		System.out.println(a9.min(a10));
		finish = System.nanoTime();
		System.out.println("MIN Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("NEGATE: ");
		start = System.nanoTime();
		System.out.println(a1.negate());
		System.out.println(a3.negate());
		System.out.println(a5.negate());
		System.out.println(a8.negate());
		finish = System.nanoTime();
		System.out.println("NEGATE Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println("ABS: ");
		start = System.nanoTime();
		System.out.println(a1.abs());
		System.out.println(a3.abs());
		System.out.println(a5.abs());
		System.out.println(a8.abs());
		finish = System.nanoTime();
		System.out.println("ABS Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println("SIGNUM: ");
		start = System.nanoTime();
		System.out.println(a2.signum());
		System.out.println(a4.signum());
		System.out.println(a6.signum());
		System.out.println(a8.signum());
		finish = System.nanoTime();
		System.out.println("SIGNUM Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println();
		System.out.println("All LinkedList Test Cases: ");
		System.out.println();
		System.out.println("ADD: ");
		start = System.nanoTime();
		System.out.println(l1.add(l2));
		System.out.println(l3.add(l4));
		System.out.println(l5.add(l6));
		System.out.println(l7.add(l8));
		System.out.println(l9.add(l10));
		finish = System.nanoTime();
		System.out.println("ADD Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("SUBTRACT: ");
		start = System.nanoTime();
		System.out.println(l1.subtract(l2));
		System.out.println(l2.subtract(l1));
		System.out.println(l3.subtract(l4));
		System.out.println(l4.subtract(l3));
		System.out.println(l5.subtract(l6));
		System.out.println(l6.subtract(l5));
		System.out.println(l7.subtract(l8));
		System.out.println(l8.subtract(l7));
		System.out.println(l9.subtract(l10));
		System.out.println(l10.subtract(l9));
		finish = System.nanoTime();
		System.out.println("SUBTRACT Runtime: " + (((finish - start) /10) /1000000.0) + ".");
		System.out.println();
		System.out.println("MAX: ");
		start = System.nanoTime();
		System.out.println(l1.max(l2));
		System.out.println(l3.max(l4));
		System.out.println(l5.max(l6));
		System.out.println(l7.max(l8));
		System.out.println(l9.max(l10));
		finish = System.nanoTime();
		System.out.println("MAX Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("MIN: ");
		start = System.nanoTime();
		System.out.println(l1.min(l2));
		System.out.println(l3.min(l4));
		System.out.println(l5.min(l6));
		System.out.println(l7.min(l8));
		System.out.println(l9.min(l10));
		finish = System.nanoTime();
		System.out.println("MIN Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("NEGATE: ");
		start = System.nanoTime();
		System.out.println(l1.negate());
		System.out.println(l3.negate());
		System.out.println(l5.negate());
		System.out.println(l8.negate());
		finish = System.nanoTime();
		System.out.println("NEGATE Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println("ABS: ");
		start = System.nanoTime();
		System.out.println(l1.abs());
		System.out.println(l3.abs());
		System.out.println(l5.abs());
		System.out.println(l8.abs());
		finish = System.nanoTime();
		System.out.println("ABS Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println("SIGNUM: ");
		start = System.nanoTime();
		System.out.println(l2.signum());
		System.out.println(l4.signum());
		System.out.println(l6.signum());
		System.out.println(l8.signum());
		finish = System.nanoTime();
		System.out.println("SIGNUM Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println();
		
		System.out.println("All BigInteger Test Cases: ");
		System.out.println();
		System.out.println("ADD: ");
		start = System.nanoTime();
		System.out.println(b1.add(b2));
		System.out.println(b3.add(b4));
		System.out.println(b5.add(b6));
		System.out.println(b7.add(b8));
		System.out.println(b9.add(b10));
		finish = System.nanoTime();
		System.out.println("ADD Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("SUBTRACT: ");
		start = System.nanoTime();
		System.out.println(b1.subtract(b2));
		System.out.println(b2.subtract(b1));
		System.out.println(b3.subtract(b4));
		System.out.println(b4.subtract(b3));
		System.out.println(b5.subtract(b6));
		System.out.println(b6.subtract(b5));
		System.out.println(b7.subtract(b8));
		System.out.println(b8.subtract(b7));
		System.out.println(b9.subtract(b10));
		System.out.println(b10.subtract(b9));
		finish = System.nanoTime();
		System.out.println("SUBTRACT Runtime: " + (((finish - start) /10) /1000000.0) + ".");
		System.out.println();
		System.out.println("MAX: ");
		start = System.nanoTime();
		System.out.println(b1.max(b2));
		System.out.println(b3.max(b4));
		System.out.println(b5.max(b6));
		System.out.println(b7.max(b8));
		System.out.println(b9.max(b10));
		finish = System.nanoTime();
		System.out.println("MAX Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("MIN: ");
		start = System.nanoTime();
		System.out.println(b1.min(b2));
		System.out.println(b3.min(b4));
		System.out.println(b5.min(b6));
		System.out.println(b7.min(b8));
		System.out.println(b9.min(b10));
		finish = System.nanoTime();
		System.out.println("MIN Runtime: " + (((finish - start) /5) /1000000.0) + ".");
		System.out.println();
		System.out.println("NEGATE: ");
		start = System.nanoTime();
		System.out.println(b1.negate());
		System.out.println(b3.negate());
		System.out.println(b5.negate());
		System.out.println(b8.negate());
		finish = System.nanoTime();
		System.out.println("NEGATE Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println("ABS: ");
		start = System.nanoTime();
		System.out.println(b1.abs());
		System.out.println(b3.abs());
		System.out.println(b5.abs());
		System.out.println(b8.abs());
		finish = System.nanoTime();
		System.out.println("ABS Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
		System.out.println("SIGNUM: ");
		start = System.nanoTime();
		System.out.println(b2.signum());
		System.out.println(b4.signum());
		System.out.println(b6.signum());
		System.out.println(b8.signum());
		finish = System.nanoTime();
		System.out.println("SIGNUM Runtime: " + (((finish - start) /4) /1000000.0) + ".");
		System.out.println();
	}

}
